[mappings]

  channels = [
    916600000,
    916800000,
    917000000,
    917200000,
    917400000,
    917600000,
    917800000,
    918000000,
    917900000,
  ]

  tx_power = [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]

  [[mappings.data_rates]]
    modulation = "LORA"
    spreading_factor = 12
    bandwidth = 125000
    code_rate = "4/5"

  [[mappings.data_rates]]
    modulation = "LORA"
    spreading_factor = 11
    bandwidth = 125000
    code_rate = "4/5"

  [[mappings.data_rates]]
    modulation = "LORA"
    spreading_factor = 10
    bandwidth = 125000
    code_rate = "4/5"

  [[mappings.data_rates]]
    modulation = "LORA"
    spreading_factor = 9
    bandwidth = 125000
    code_rate = "4/5"

  [[mappings.data_rates]]
    modulation = "LORA"
    spreading_factor = 8
    bandwidth = 125000
    code_rate = "4/5"

  [[mappings.data_rates]]
    modulation = "LORA"
    spreading_factor = 7
    bandwidth = 125000
    code_rate = "4/5"

  [[mappings.data_rates]]
    modulation = "LORA"
    spreading_factor = 7
    bandwidth = 250000
    code_rate = "4/5"

  [[mappings.data_rate]]
    modulation = "FSK"
    bitrate = 50000
